kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: react-app-demo
  namespace: react-app-demo
  labels:
    app.kubernetes.io/instance: react-web-argo-application
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: app
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: app-0.1.0
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: react-app-demo-react-app-demo.apps.cluster-nlv9x.dynamic.redhatworkshops.io
  to:
    kind: Service
    name: react-web-argo-application
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None